# Generated by Django 3.2.5 on 2022-07-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0002_auto_20220722_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='comics', to='comics.Category'),
        ),
    ]
