# Generated by Django 3.2.5 on 2022-07-26 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0004_auto_20220726_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['-id']},
        ),
    ]
