# Generated by Django 3.2.5 on 2022-07-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0006_comment_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m'),
        ),
    ]
