# Generated by Django 3.2.5 on 2022-10-25 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0007_product_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_id',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
