# Generated by Django 3.2.5 on 2022-08-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0008_comment_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_num',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('slug', 'chapter_num')},
        ),
    ]
