# Generated by Django 3.2.5 on 2022-10-25 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0009_auto_20221025_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stripe_price_id',
        ),
    ]
