# Generated by Django 3.2.5 on 2022-10-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0010_remove_product_stripe_price_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price_id',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
