# Generated by Django 3.2.5 on 2022-08-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0010_alter_chapter_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('chapter_num', 'comic')},
        ),
    ]
