# Generated by Django 3.2.5 on 2022-08-04 09:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0011_alter_chapter_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=True, populate_from='chapter_num'),
        ),
    ]
