# Generated by Django 3.2.5 on 2022-10-26 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0012_auto_20221026_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coin',
        ),
    ]
