# Generated by Django 3.2.5 on 2022-11-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0014_auto_20221103_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
