# Generated by Django 3.2.5 on 2022-11-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0015_auto_20221103_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
