# Generated by Django 3.2.5 on 2022-11-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0016_alter_chapter_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='category',
            field=models.CharField(choices=[('C', 'COIN'), ('CH', 'CHAPTER')], default='C', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('C', 'COIN'), ('CH', 'CHAPTER')], default='C', max_length=2),
        ),
    ]
