# Generated by Django 3.2.5 on 2022-11-12 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0017_auto_20221103_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterimage',
            name='chapter',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapter_images', to='comics.chapter'),
        ),
    ]
