# Generated by Django 3.2.5 on 2022-11-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0019_auto_20221112_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
