# Generated by Django 3.2.5 on 2022-11-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0020_alter_payment_stripe_charge_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
