# Generated by Django 3.2.5 on 2022-07-22 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comic',
            name='category',
        ),
        migrations.AddField(
            model_name='comic',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='comics', to='comics.Category'),
        ),
        migrations.CreateModel(
            name='ComicView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
                ('comic', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='comics.comic')),
            ],
        ),
    ]
