# Generated by Django 3.2.5 on 2022-08-15 10:12

import comics.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='chapter_num',
            field=models.PositiveIntegerField(default=comics.models.default_chapter_num),
        ),
        migrations.AlterField(
            model_name='comic',
            name='posted_by',
            field=models.ForeignKey(default=comics.models.User, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
