# Generated by Django 3.2.5 on 2022-07-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0003_alter_comic_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comic',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='comic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='comics.comic'),
        ),
    ]
